# Generated by Django 2.2.1 on 2019-06-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264, unique=True)),
                ('image_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.IntegerField(unique=True)),
                ('quote_text', models.CharField(max_length=264, unique=True)),
                ('quote_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_wqit.Person')),
            ],
        ),
    ]
